package withpatterns.repository.impl;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.JdbcTest;
import org.springframework.context.annotation.Import;
import org.springframework.jdbc.core.JdbcTemplate;
import withpatterns.dto.UserRequest;

import static org.junit.jupiter.api.Assertions.*;

@JdbcTest
@Import(JdbcUserRepository.class)
class JdbcUserRepositoryTest {

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private JdbcUserRepository repository;

    @BeforeEach
    void setupSchema() {
        jdbcTemplate.execute("""
            CREATE TABLE IF NOT EXISTS users (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              name VARCHAR(120) NOT NULL,
              email VARCHAR(200) NOT NULL,
              password VARCHAR(200) NOT NULL,
              cpf VARCHAR(11) NOT NULL
            )
        """);
    }

    @Test
    void save_findById_findAll_update_delete_shouldWork() {
        var req = new UserRequest("Tuany", "tuany@exemplo.com", "Senha123", "12345678901");

        var created = repository.save(req);
        assertNotNull(created);
        assertNotNull(created.id());

        var byId = repository.findById(created.id());
        assertTrue(byId.isPresent());

        var list = repository.findAll();
        assertFalse(list.isEmpty());

        var updated = repository.update(
                created.id(),
                new UserRequest("Tuany2", "tuany2@exemplo.com", "Senha123", "12345678901")
        );
        assertNotNull(updated);

        assertTrue(repository.delete(created.id()));
        assertTrue(repository.findById(created.id()).isEmpty());
    }

    @Test
    void update_shouldReturnNullWhenNotFound() {
        var req = new UserRequest("A", "a@b.com", "Senha123", "12345678901");
        assertNull(repository.update(999L, req));
    }

    @Test
    void delete_shouldReturnFalseWhenNotFound() {
        assertFalse(repository.delete(999L));
    }
}