CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     name VARCHAR(120) NOT NULL,
    email VARCHAR(200) NOT NULL,
    password VARCHAR(200) NOT NULL,
    cpf VARCHAR(11) NOT NULL
    );

CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email ON users(email);
